version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "examples/create-react-app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/icons/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/styles/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "packages/web/"
    schedule:
      interval: "daily"
