template: |
  ## What’s Changed

  $CHANGES
  
  ---
  
  If you have ideas or suggestions how to make our Design System even better please send us an issue:
  https://github.com/natura-cosmeticos/natds-js/issues
