cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
jobs:
  include:
    - stage: Sanity Check
      script: yarn verify:ci
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
        on:
          all_branches: true
language: node_js
node_js:
  - 10.21.0
