---
language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
  yarn:
    true
git:
  quiet: true
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
jobs:
  include:
    - stage: sanity-check
      name: "Sanity check"
      script: yarn run verify:ci
    - stage: pre-release
      name: "Pre-release"
      if: type = push AND branch =~ /^DSY-(\d+)$/
      before_script:
        - "sh ./scripts/configure-git.sh"
        - "yarn run prerelease --force-publish --yes --preid alpha.$TRAVIS_BRANCH"
      script: "yarn run lerna:publish --yes --pre-dist-tag $TRAVIS_BRANCH"
      after_script: "sh ./scripts/build-storybook-prerelease.sh"
    - stage: release
      name: "Release"
      if: type = push AND branch = master
      script: skip
      before_deploy:
        - "sh ./scripts/configure-git.sh"
        - "yarn run release --force-publish --yes --create-release github"
      deploy:
        - provider: script
          script: "yarn run lerna:publish --yes"
          skip_cleanup: true
          on:
            branch: master
      after_deploy: "sh ./scripts/build-storybook.sh"
