language: node_js

node_js:
  - 10.16.3

cache:
  directories:
    - node_modules
    - packages/web/node_modules
    - packages/mobile/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules

branches:
  only:
    - master
    - /v([0-9]+)\.([0-9]+)\.([0-9]+)\w+$/    # Milestone branch pattern for vM.m.p

jobs:
  include:
    - stage: Unit Tests
      script: yarn verify
    - stage: Bump Alpha Version
      if: branch =~ /v([0-9]+)\.([0-9]+)\.([0-9]+)\w+$/ AND type = push AND commit_message !=~ /^Travis Commit:(.+)$/
      script: scripts/bump-alpha-version.sh
    - stage: Build Alpha Storybook Version
      if: branch =~ /v([0-9]+)\.([0-9]+)\.([0-9]+)\w+$/ AND type = push AND commit_message !=~ /^Travis Commit:(.+)$/
      script: scripts/build-pre-release.sh


