---
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
  yarn:
    true
dist: xenial
jobs:
  include:
    - stage: dependency-check
      if: "NOT (branch = master) AND branch =~ /^dependabot\\/(.+)$/ OR branch =~ /^renovate\\/(.+)$/"
      script: "yarn test"
    - stage: prerelease
      if: "NOT (branch = master) AND branch =~ /^DSY-(\\d+)$/"
      before_script:
        - "git remote rm origin"
        - "git remote add origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/natura-cosmeticos/natds-js"
        - "git fetch"
        - "git checkout $TRAVIS_BRANCH"
        - "git config --global user.email \"travis@travis-ci.org\""
        - "git config --global user.name \"$GITHUB_API_USER by Travis CI\""
        - "npm config set '//registry.npmjs.org/:_authToken' \"${NPM_AUTH_TOKEN}\""
        - "yarn config set _authToken ${NPM_AUTH_TOKEN}"
      script: "yarn prerelease:ci alpha-$TRAVIS_BRANCH && yarn lerna:publish:ci"
    - stage: release
      if: "branch = master AND NOT (commit_message =~ /^Travis Commit:(.+)$/ OR commit_message =~ /^Publish(.*)$/ OR commit_message =~ /^(.*)[skip ci]$/)"
      before_deploy:
        - "git remote rm origin"
        - "git remote add origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/natura-cosmeticos/natds-js"
        - "git fetch"
        - "git checkout $TRAVIS_BRANCH"
        - "git config --global user.email \"travis@travis-ci.org\""
        - "git config --global user.name \"$GITHUB_API_USER by Travis CI\""
        - "npm config set '//registry.npmjs.org/:_authToken' \"${NPM_AUTH_TOKEN}\""
        - "yarn config set _authToken ${NPM_AUTH_TOKEN}"
      deploy:
        provider: script
        script: "yarn release:ci && yarn lerna:publish:ci"
        after_deploy: "chmod +x scripts/build-storybook.sh && scripts/build-storybook.sh"
        skip_cleanup: true
        on:
          branch: master
language: node_js
node_js:
  - lts/*
os: linux
