---
language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
  yarn:
    true
git:
  quiet: true
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
env: GH_TOKEN=${GITHUB_TOKEN}
jobs:
  include:
    - stage: release
      name: "Release"
      script: yarn run verify:ci
      before_deploy:
        - "git remote rm origin"
        - "git remote add origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/natura-cosmeticos/natds-js"
        - "git fetch"
        - "git checkout $TRAVIS_BRANCH"
        - "git config --global user.email \"systemteamopensource@natura.net\""
        - "git config --global user.name \"$GITHUB_API_USER by Travis CI\""
        - "npm config set '//registry.npmjs.org/:_authToken' \"${NPM_AUTH_TOKEN}\""
        - "yarn config set _authToken ${NPM_AUTH_TOKEN}"
      deploy:
        - provider: script
          script: "yarn run prerelease:ci alpha-$TRAVIS_BRANCH && yarn run lerna:publish:ci"
          skip_cleanup: true
          on:
            all_branches: true
            condition: branch =~ ^DSY-(\\d+)$
        - provider: script
          script: "yarn run release:ci && yarn run lerna:publish:ci"
          skip_cleanup: true
          on:
            branch: master
