---
branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
  yarn:
    true
dist: xenial
jobs:
  include:
    - stage: dependency-check
      name: "Dependency check"
      if: "true AND NOT (commit_message =~ /^(.*)[skip ci]$/)"
      script: "yarn test"
    - stage: prerelease
      name: "Pre-release"
      if: "branch != master AND branch =~ /^DSY-(\\d+)$/"
      before_script:
        - "git remote rm origin"
        - "git remote add origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/natura-cosmeticos/natds-js"
        - "git fetch"
        - "git checkout $TRAVIS_BRANCH"
        - "git config --global user.email \"systemteamopensource@natura.net\""
        - "git config --global user.name \"$GITHUB_API_USER by Travis CI\""
        - "npm config set '//registry.npmjs.org/:_authToken' \"${NPM_AUTH_TOKEN}\""
        - "yarn config set _authToken ${NPM_AUTH_TOKEN}"
      script: "echo \"Preparing pre-release...\" && yarn prerelease:ci alpha-$TRAVIS_BRANCH && yarn lerna:publish:ci"
    - stage: release
      name: "Release and Storybook build"
      if: "branch = master AND NOT (commit_message =~ /^(.*)[skip ci]$/)"
      script: skip # usually you do not want to rerun any tests
      before_deploy:
        - "git remote rm origin"
        - "git remote add origin https://$GITHUB_API_USER:$GITHUB_API_KEY@github.com/natura-cosmeticos/natds-js"
        - "git fetch"
        - "git checkout $TRAVIS_BRANCH"
        - "git config --global user.email \"systemteamopensource@natura.net\""
        - "git config --global user.name \"$GITHUB_API_USER by Travis CI\""
        - "npm config set '//registry.npmjs.org/:_authToken' \"${NPM_AUTH_TOKEN}\""
        - "yarn config set _authToken ${NPM_AUTH_TOKEN}"
      deploy:
        provider: script
        script: "echo \"Preparing release...\" && yarn release:ci && yarn lerna:publish:ci"
        skip_cleanup: true
        on:
          branch: master
      after_deploy: "chmod +x scripts/build-storybook.sh && scripts/build-storybook.sh"
language: node_js
node_js:
  - lts/*
os: linux
