# Branch patterns:
#
# dependabot: /^dependabot\/(.+)$/
# docs:       /v\d+\.\d+\.\d+-docs$/
# feature:    /^feature\/(.+)$/
# hotfix:     /^hotfix\/(.+)$/
# jira:       /^DSY-(\d+)$/
# milestone:  /v\d+\.\d+\.\d+$/
# renovate:   /^renovate\/(.+)$/
# storybook:  master-docs

branches:
  except:
    - /v\d+\.\d+\.\d+$/
    - /v\d+\.\d+\.\d+-docs$/
cache:
  directories:
    - node_modules
    - packages/icons/node_modules
    - packages/web/node_modules
    - packages/styles/node_modules
    - packages/docs/node_modules
jobs:
  include:
    - stage: dependency-check
        if: branch =~ /^dependabot\/(.+)$/ OR branch =~ /^renovate\/(.+)$/
        script: echo "yarn verify:ci"
    - stage: prerelease
        if: branch =~ /^DSY-(\d+)$/ OR branch =~ /^feature\/(.+)$/ OR branch =~ /^hotfix\/(.+)$/
        deploy:
          provider: script
          skip_cleanup: true
          script:
            - echo "yarn prerelease $TRAVIS_BRANCH && yarn publish"
    - stage: release
      if: branch = master
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - echo "yarn release && yarn publish"
language: node_js
node_js:
  - lts/*

