dictionaries:
  - en
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "*.tsx.snap"
  - "packages/icons/src/natds-icons.swift"
  - "node_modules/**/*"
  - "packages/docs/dist/**/*"
excluded_words:
  - Aboukhadijeh
  - Ashkenas
  - brand
  - cjs
  - date-fns
  - dedupe
  - feross
  - fileurl
  - filled
  - filled-brand-naturarosacea
  - filled-navigation
  - Fira
  - FiraCode-Retina
  - Holowaychuk
  - iml
  - Isonen
  - javascript-mutator
  - Kirollos
  - Lubbe
  - Lichtnow
  - Lucida
  - Lyrio
  - Matheus
  - natds
  - natDsIcons
  - natdsIcons
  - natds-icons
  - natds-styles
  - natds-web
  - natdsWeb
  - natura
  - naturacosmeticos
  - naturarosacea
  - Nunito
  - outlined
  - outlined-action
  - outlined-action-lightoff
  - outlined-action-lighton
  - outlined-action-selectedalllines
  - outlined-action-shareios
  - outlined-content
  - outlined-content-christmascard
  - outlined-content-planb
  - outlined-default-mockup
  - outlined-finance-shoppingcartproduct
  - outlined-place-waze
  - outlined-social-groupofpeople
  - preferBuiltins
  - Saraiva
  - Schlinkert
  - Sindre
  - Slobodskoi
  - Sorhus
  - stryker-mutator
  - tcm
  - Tiancheng
  - transpilers
  - typoci
  - Vagner
  - Vizir
  - Zivolo
