dictionaries:
  - en
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "*.tsx.snap"
  - "packages/icons/src/natds-icons.swift"
  - "node_modules/**/*"
  - "packages/docs/dist/**/*"
excluded_words:
  - Aboukhadijeh
  - Ashkenas
  - cjs
  - date-fns
  - feross
  - fileurl
  - Fira
  - FiraCode-Retina
  - Holowaychuk
  - iml
  - Isonen
  - javascript-mutator
  - Kirollos
  - Lubbe
  - Lichtnow
  - Lucida
  - Lyrio
  - Matheus
  - natds
  - natDsIcons
  - natdsIcons
  - natds-icons
  - natds-styles
  - natds-web
  - natdsWeb
  - natura
  - naturacosmeticos
  - Nunito
  - preferBuiltins
  - Saraiva
  - Schlinkert
  - Sindre
  - Slobodskoi
  - Sorhus
  - stryker-mutator
  - tcm
  - Tiancheng
  - transpilers
  - typoci
  - Vagner
  - Vizir
  - Zivolo
